-- This script defines the schema for the Structured Credit CRM.
-- It's designed for Databricks SQL and Delta Lake, within the cri.crm schema.

-- Main table for credit operations
CREATE TABLE IF NOT EXISTS cri.crm.operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL,
    operation_type STRING,
    maturity_date TIMESTAMP,
    responsible_analyst STRING,
    review_frequency STRING,
    call_frequency STRING,
    df_frequency STRING,
    segmento STRING,
    rating_operation STRING,
    rating_group STRING,
    watchlist STRING,
    ltv FLOAT,
    dscr FLOAT,
    monitoring_news BOOLEAN,
    monitoring_fii_report BOOLEAN,
    monitoring_operational_info BOOLEAN,
    monitoring_receivables_portfolio BOOLEAN,
    monitoring_construction_report BOOLEAN,
    monitoring_commercial_info BOOLEAN,
    monitoring_spe_dfs BOOLEAN
);

-- Projects associated with operations
CREATE TABLE IF NOT EXISTS cri.crm.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL
);

-- Join table for the many-to-many relationship between operations and projects
CREATE TABLE IF NOT EXISTS cri.crm.operation_projects (
    operation_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    PRIMARY KEY (operation_id, project_id),
    FOREIGN KEY (operation_id) REFERENCES cri.crm.operations(id),
    FOREIGN KEY (project_id) REFERENCES cri.crm.projects(id)
);

-- Guarantees associated with operations
CREATE TABLE IF NOT EXISTS cri.crm.guarantees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL
);

-- Join table for the many-to-many relationship between operations and guarantees
CREATE TABLE IF NOT EXISTS cri.crm.operation_guarantees (
    operation_id BIGINT NOT NULL,
    guarantee_id BIGINT NOT NULL,
    PRIMARY KEY (operation_id, guarantee_id),
    FOREIGN KEY (operation_id) REFERENCES cri.crm.operations(id),
    FOREIGN KEY (guarantee_id) REFERENCES cri.crm.guarantees(id)
);

-- Events related to each operation
CREATE TABLE IF NOT EXISTS cri.crm.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    date TIMESTAMP,
    type STRING,
    title STRING,
    description STRING,
    registered_by STRING,
    next_steps STRING,
    completed_task_id STRING,
    FOREIGN KEY (operation_id) REFERENCES cri.crm.operations(id)
);

-- Task rules that generate recurring or one-off tasks
CREATE TABLE IF NOT EXISTS cri.crm.task_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    name STRING,
    frequency STRING,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    description STRING,
    FOREIGN KEY (operation_id) REFERENCES cri.crm.operations(id)
);

-- History of rating and sentiment changes for each operation
CREATE TABLE IF NOT EXISTS cri.crm.rating_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    event_id BIGINT,
    date TIMESTAMP,
    rating_operation STRING,
    rating_group STRING,
    sentiment STRING,
    FOREIGN KEY (operation_id) REFERENCES cri.crm.operations(id),
    FOREIGN KEY (event_id) REFERENCES cri.crm.events(id)
);