-- Final CRM Schema Definition Script
-- Created automatically from update_db.py SCHEMA definition.
CREATE SCHEMA IF NOT EXISTS cri_cra_dev.crm;
USE cri_cra_dev.crm;

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.master_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL,
    sector STRING,
    rating STRING
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.economic_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_group_id BIGINT NOT NULL,
    name STRING NOT NULL,
    sector STRING,
    rating STRING,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.master_group_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_group_id BIGINT NOT NULL,
    name STRING NOT NULL,
    email STRING,
    phone STRING,
    role STRING
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL,
    area STRING,
    operation_type STRING,
    maturity_date TIMESTAMP,
    responsible_analyst STRING,
    review_frequency STRING,
    call_frequency STRING,
    df_frequency STRING,
    segmento STRING,
    rating_operation STRING,
    rating_group STRING,
    watchlist STRING,
    ltv FLOAT,
    dscr FLOAT,
    monitoring_news BOOLEAN,
    monitoring_fii_report BOOLEAN,
    monitoring_operational_info BOOLEAN,
    monitoring_receivables_portfolio BOOLEAN,
    monitoring_construction_report BOOLEAN,
    monitoring_commercial_info BOOLEAN,
    monitoring_spe_dfs BOOLEAN,
    status STRING,
    description STRING,
    moved_to_legacy_date TIMESTAMP,
    master_group_id BIGINT,
    economic_group_id BIGINT,
    is_structuring BOOLEAN,
    pipeline_stage STRING,
    rate STRING,
    indexer STRING,
    volume FLOAT,
    fund STRING,
    risk STRING,
    temperature STRING,
    liquidation_date TIMESTAMP,
    is_active BOOLEAN,
    originator STRING,
    modality STRING,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    name STRING NOT NULL,
    rate STRING,
    indexer STRING,
    volume FLOAT,
    fund STRING,
    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    name STRING NOT NULL,
    order_index INT NOT NULL,
    is_completed BOOLEAN
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL,
    status STRING,
    state STRING,
    city STRING
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.guarantees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL,
    type STRING,
    value FLOAT,
    description STRING
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_projects (
    operation_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    PRIMARY KEY (operation_id, project_id)
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_guarantees (
    operation_id BIGINT NOT NULL,
    guarantee_id BIGINT NOT NULL,
    PRIMARY KEY (operation_id, guarantee_id)
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.rating_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT,
    master_group_id BIGINT,
    date TIMESTAMP NOT NULL,
    rating_operation STRING NOT NULL,
    rating_group STRING NOT NULL,
    watchlist STRING,
    sentiment STRING,
    event_id BIGINT
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT,
    master_group_id BIGINT,
    date TIMESTAMP NOT NULL,
    type STRING NOT NULL,
    title STRING NOT NULL,
    description STRING NOT NULL,
    registered_by STRING NOT NULL,
    next_steps STRING,
    completed_task_id STRING,
    attention_points STRING,
    our_attendees STRING,
    operation_attendees STRING,
    is_origination BOOLEAN,
    operation_stage_id BIGINT
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.task_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT,
    name STRING NOT NULL,
    frequency STRING NOT NULL,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    description STRING,
    priority STRING,
    is_origination BOOLEAN,
    operation_stage_id BIGINT
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_review_notes (
    operation_id BIGINT PRIMARY KEY,
    notes STRING,
    updated_at TIMESTAMP NOT NULL,
    updated_by STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.task_exceptions (
    task_id STRING PRIMARY KEY,
    operation_id BIGINT,
    deleted_at TIMESTAMP,
    deleted_by STRING
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    user_name STRING NOT NULL,
    action STRING NOT NULL,
    entity_type STRING NOT NULL,
    entity_id STRING NOT NULL,
    details STRING
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.change_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title STRING NOT NULL,
    description STRING NOT NULL,
    requester STRING NOT NULL,
    status STRING NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.patch_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version STRING NOT NULL,
    date TIMESTAMP NOT NULL,
    title STRING NOT NULL,
    description STRING NOT NULL,
    changes STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.sync_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    data STRING NOT NULL,
    created_at TIMESTAMP,
    processed BOOLEAN
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.analyst_notes (
    analyst_name STRING PRIMARY KEY,
    notes STRING,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_risks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT,
    master_group_id BIGINT,
    title STRING NOT NULL,
    description STRING,
    severity STRING,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.fund_allocation_inputs (
    fund_name STRING PRIMARY KEY,
    emission FLOAT,
    prepayment FLOAT,
    repurchases FLOAT,
    new_repo FLOAT,
    updated_at TIMESTAMP
);

