import os
import json
from datetime import datetime
from db import get_db_connection

def update_schema():
    conn = get_db_connection()
    try:
        with conn.cursor() as cursor:
            print("Checking if priority column exists in task_rules...")
            cursor.execute("DESCRIBE cri_cra_dev.crm.task_rules")
            columns = [row.col_name for row in cursor.fetchall()]
            
            if 'priority' not in columns:
                print("Adding priority column...")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.task_rules ADD COLUMN priority STRING COMMENT 'Prioridade da tarefa (Alta, Média, Baixa).'")
                print("Column added successfully.")
            else:
                print("Column priority already exists.")

            print("Ensuring task_rules dates are nullable...")
            # In Databricks SQL, we use ALTER TABLE ALTER COLUMN
            cursor.execute("ALTER TABLE cri_cra_dev.crm.task_rules ALTER COLUMN start_date DROP NOT NULL")
            cursor.execute("ALTER TABLE cri_cra_dev.crm.task_rules ALTER COLUMN end_date DROP NOT NULL")
            print("Dates are now nullable.")

            print("Ensuring operation_review_notes table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_review_notes (
                    operation_id BIGINT PRIMARY KEY,
                    notes STRING,
                    updated_at TIMESTAMP NOT NULL,
                    updated_by STRING NOT NULL,
                    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
                ) COMMENT 'Armazena notas e observações editáveis para cada operação.'
            """)
            print("Table operation_review_notes checked/created.")

            print("Ensuring change_requests table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.change_requests (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title STRING NOT NULL,
                    description STRING NOT NULL,
                    requester STRING NOT NULL,
                    status STRING NOT NULL DEFAULT 'pending' COMMENT 'Status da solicitação: pending, completed.',
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL
                ) COMMENT 'Armazena solicitações de mudanças e novas funcionalidades feitas pelos usuários.'
            """)
            print("Table change_requests checked/created.")

            print("Ensuring patch_notes table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.patch_notes (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    version STRING NOT NULL,
                    date TIMESTAMP NOT NULL,
                    title STRING NOT NULL,
                    description STRING NOT NULL,
                    changes STRING NOT NULL COMMENT 'Lista de mudanças serializada como JSON.'
                ) COMMENT 'Armazena o histórico de versões e melhorias implementadas no sistema.'
            """)
            print("Table patch_notes checked/created.")

            print("Checking if analyst_notes table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.analyst_notes (
                    analyst_name STRING PRIMARY KEY,
                    notes STRING,
                    updated_at TIMESTAMP NOT NULL
                ) COMMENT 'Armazena notas gerais (post-it) para cada analista.'
            """)
            print("Table analyst_notes checked/created.")

            print("Checking if description column exists in operations...")
            cursor.execute("DESCRIBE cri_cra_dev.crm.operations")
            op_columns = [row.col_name for row in cursor.fetchall()]
            if 'description' not in op_columns:
                print("Adding description column to operations...")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN description STRING COMMENT 'Descrição detalhada da operação.'")
                print("Column description added successfully.")

            print("Ensuring operation_risks table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_risks (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT NOT NULL,
                    title STRING NOT NULL,
                    description STRING,
                    severity STRING DEFAULT 'Média' COMMENT 'Severidade: Baixa, Média, Alta.',
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL
                ) COMMENT 'Armazena riscos e pontos de atenção identificados para cada operação.'
            """)
            print("Table operation_risks checked/created.")

            print("Checking if patch_notes is empty...")
            cursor.execute("SELECT COUNT(*) as count FROM cri_cra_dev.crm.patch_notes")
            if cursor.fetchone().count == 0:
                print("Adding initial patch notes...")
                initial_changes = json.dumps([
                    "Implementação inicial do CRM de Crédito Estruturado",
                    "Gestão de operações de CRI e CRA",
                    "Monitoramento de tarefas e revisões periódicas",
                    "Hub do Analista para visão consolidada",
                    "Log de auditoria para rastreabilidade"
                ])
                cursor.execute("""
                    INSERT INTO cri_cra_dev.crm.patch_notes (version, date, title, description, changes)
                    VALUES (?, ?, ?, ?, ?)
                """, ("1.0.0", datetime.now(), "Lançamento Inicial", "Primeira versão estável do sistema CRM.", initial_changes))
                print("Initial patch notes added.")
    except Exception as e:
        print(f"Error updating schema: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    update_schema()
