import os
import json
from datetime import datetime
from db import get_db_connection

def update_schema():
    conn = get_db_connection()
    try:
        with conn.cursor() as cursor:
            print("Ensuring operations table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operations (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name STRING NOT NULL,
                    area STRING NOT NULL,
                    operation_type STRING NOT NULL,
                    maturity_date TIMESTAMP NOT NULL,
                    responsible_analyst STRING NOT NULL,
                    review_frequency STRING NOT NULL,
                    call_frequency STRING NOT NULL,
                    df_frequency STRING NOT NULL,
                    segmento STRING,
                    rating_operation STRING NOT NULL,
                    rating_group STRING NOT NULL,
                    watchlist STRING NOT NULL,
                    ltv FLOAT,
                    dscr FLOAT,
                    monitoring_news BOOLEAN,
                    monitoring_fii_report BOOLEAN,
                    monitoring_operational_info BOOLEAN,
                    monitoring_receivables_portfolio BOOLEAN,
                    monitoring_construction_report BOOLEAN,
                    monitoring_commercial_info BOOLEAN,
                    monitoring_spe_dfs BOOLEAN,
                    status STRING,
                    description STRING
                )
            """)
            print("Table operations checked/created.")

            print("Ensuring events table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT NOT NULL,
                    date TIMESTAMP NOT NULL,
                    type STRING NOT NULL,
                    title STRING NOT NULL,
                    description STRING NOT NULL,
                    registered_by STRING NOT NULL,
                    next_steps STRING,
                    completed_task_id STRING,
                    attention_points STRING,
                    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
                )
            """)
            print("Table events checked/created.")

            print("Ensuring task_rules table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.task_rules (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT NOT NULL,
                    name STRING NOT NULL,
                    frequency STRING NOT NULL,
                    start_date TIMESTAMP NOT NULL,
                    end_date TIMESTAMP NOT NULL,
                    description STRING,
                    priority STRING,
                    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
                )
            """)
            print("Table task_rules checked/created.")

            print("Checking if priority column exists in task_rules...")
            cursor.execute("DESCRIBE cri_cra_dev.crm.task_rules")
            columns = [row.col_name for row in cursor.fetchall()]
            
            if 'priority' not in columns:
                print("Adding priority column...")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.task_rules ADD COLUMN priority STRING COMMENT 'Prioridade da tarefa (Alta, Média, Baixa).'")
                print("Column added successfully.")
            else:
                print("Column priority already exists.")

            print("Ensuring task_rules dates are nullable...")
            # In Databricks SQL, we use ALTER TABLE ALTER COLUMN
            cursor.execute("ALTER TABLE cri_cra_dev.crm.task_rules ALTER COLUMN start_date DROP NOT NULL")
            cursor.execute("ALTER TABLE cri_cra_dev.crm.task_rules ALTER COLUMN end_date DROP NOT NULL")
            print("Dates are now nullable.")

            print("Ensuring operation_review_notes table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_review_notes (
                    operation_id BIGINT PRIMARY KEY,
                    notes STRING,
                    updated_at TIMESTAMP NOT NULL,
                    updated_by STRING NOT NULL,
                    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
                ) COMMENT 'Armazena notas e observações editáveis para cada operação.'
            """)
            print("Table operation_review_notes checked/created.")

            print("Ensuring audit_logs table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.audit_logs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    timestamp TIMESTAMP NOT NULL,
                    user_name STRING NOT NULL,
                    action STRING NOT NULL COMMENT 'Ação realizada: CREATE, UPDATE, DELETE.',
                    entity_type STRING NOT NULL COMMENT 'Tipo da entidade afetada: Operation, Event, etc.',
                    entity_id STRING NOT NULL COMMENT 'ID da entidade afetada.',
                    details STRING COMMENT 'Descrição detalhada da alteração.'
                ) COMMENT 'Trilha de auditoria para todas as modificações de dados no CRM.'
            """)
            print("Table audit_logs checked/created.")

            print("Ensuring change_requests table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.change_requests (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title STRING NOT NULL,
                    description STRING NOT NULL,
                    requester STRING NOT NULL,
                    status STRING NOT NULL COMMENT 'Status da solicitação: pending, completed.',
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL
                ) COMMENT 'Armazena solicitações de mudanças e novas funcionalidades feitas pelos usuários.'
            """)
            print("Table change_requests checked/created.")

            print("Ensuring patch_notes table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.patch_notes (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    version STRING NOT NULL,
                    date TIMESTAMP NOT NULL,
                    title STRING NOT NULL,
                    description STRING NOT NULL,
                    changes STRING NOT NULL COMMENT 'Lista de mudanças serializada como JSON.'
                ) COMMENT 'Armazena o histórico de versões e melhorias implementadas no sistema.'
            """)
            print("Table patch_notes checked/created.")
            
            print("Ensuring sync_queue table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.sync_queue (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT NOT NULL,
                    data STRING NOT NULL COMMENT 'Dados da operação serializados como JSON.',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    processed BOOLEAN DEFAULT FALSE
                ) COMMENT 'Fila de sincronização para lidar com latência do Databricks.'
            """)
            print("Table sync_queue checked/created.")

            print("Checking if analyst_notes table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.analyst_notes (
                    analyst_name STRING PRIMARY KEY,
                    notes STRING,
                    updated_at TIMESTAMP NOT NULL
                ) COMMENT 'Armazena notas gerais (post-it) para cada analista.'
            """)
            print("Table analyst_notes checked/created.")

            print("Checking if description column exists in operations...")
            cursor.execute("DESCRIBE cri_cra_dev.crm.operations")
            op_columns = [row.col_name.lower() for row in cursor.fetchall()]
            if 'description' not in op_columns:
                print("Adding description column to operations...")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN description STRING COMMENT 'Descrição detalhada da operação.'")
                print("Column description added successfully.")

            if 'status' not in op_columns:
                print("Adding status column to operations...")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN status STRING COMMENT 'Status da operação (Ativa, Legado).'")
                print("Column status added successfully.")

            print("Ensuring operation_risks table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_risks (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT NOT NULL,
                    title STRING NOT NULL,
                    description STRING,
                    severity STRING COMMENT 'Severidade: Baixa, Média, Alta.',
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL
                ) COMMENT 'Armazena riscos e pontos de atenção identificados para cada operação.'
            """)
            print("Table operation_risks checked/created.")
            
            print("Checking if attention_points column exists in events...")
            cursor.execute("DESCRIBE cri_cra_dev.crm.events")
            event_columns = [row.col_name for row in cursor.fetchall()]
            if 'attention_points' not in event_columns:
                print("Adding attention_points column to events...")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.events ADD COLUMN attention_points STRING COMMENT 'Pontos de atenção registrados na revisão.'")
                print("Column attention_points added successfully.")
            if 'our_attendees' not in event_columns:
                print("Adding our_attendees column to events...")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.events ADD COLUMN our_attendees STRING COMMENT 'Pessoas presentes por parte da nossa empresa.'")
                print("Column our_attendees added successfully.")
            if 'operation_attendees' not in event_columns:
                print("Adding operation_attendees column to events...")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.events ADD COLUMN operation_attendees STRING COMMENT 'Pessoas presentes na empresa da operação.'")
                print("Column operation_attendees added successfully.")

            print("Checking if patch_notes is empty...")
            cursor.execute("SELECT COUNT(*) as count FROM cri_cra_dev.crm.patch_notes")
            if cursor.fetchone().count == 0:
                print("Adding initial patch notes...")
                initial_changes = json.dumps([
                    "Implementação inicial do CRM de Crédito Estruturado",
                    "Gestão de operações de CRI e CRA",
                    "Monitoramento de tarefas e revisões periódicas",
                    "Hub do Analista para visão consolidada",
                    "Log de auditoria para rastreabilidade"
                ])
                cursor.execute("""
                    INSERT INTO cri_cra_dev.crm.patch_notes (version, date, title, description, changes)
                    VALUES (?, ?, ?, ?, ?)
                """, ("1.0.0", datetime.now(), "Lançamento Inicial", "Primeira versão estável do sistema CRM.", initial_changes))
                print("Initial patch notes added.")
    except Exception as e:
        print(f"Error updating schema: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    update_schema()
