import os
import json
import re
from datetime import datetime
from db import get_db_connection

# Define all tables and their columns
SCHEMA = {
    "cri_cra_dev.crm.master_groups": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "name STRING NOT NULL",
        "sector STRING",
        "rating STRING"
    ],
    "cri_cra_dev.crm.master_group_contacts": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "master_group_id BIGINT NOT NULL",
        "name STRING NOT NULL",
        "email STRING",
        "phone STRING",
        "role STRING"
    ],
    "cri_cra_dev.crm.operations": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "name STRING NOT NULL",
        "area STRING",
        "operation_type STRING",
        "maturity_date TIMESTAMP",
        "responsible_analyst STRING",
        "review_frequency STRING",
        "call_frequency STRING",
        "df_frequency STRING",
        "segmento STRING",
        "rating_operation STRING",
        "rating_group STRING",
        "watchlist STRING",
        "ltv FLOAT",
        "dscr FLOAT",
        "monitoring_news BOOLEAN",
        "monitoring_fii_report BOOLEAN",
        "monitoring_operational_info BOOLEAN",
        "monitoring_receivables_portfolio BOOLEAN",
        "monitoring_construction_report BOOLEAN",
        "monitoring_commercial_info BOOLEAN",
        "monitoring_spe_dfs BOOLEAN",
        "status STRING",
        "description STRING",
        "moved_to_legacy_date TIMESTAMP",
        "master_group_id BIGINT",
        "is_structuring BOOLEAN",
        "pipeline_stage STRING",
        "rate STRING",
        "indexer STRING",
        "volume FLOAT",
        "fund STRING",
        "risk STRING",
        "temperature STRING",
        "liquidation_date TIMESTAMP",
        "is_active BOOLEAN",
        "originator STRING",
        "modality STRING"
    ],
    "cri_cra_dev.crm.operation_series": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT NOT NULL",
        "name STRING NOT NULL",
        "rate STRING",
        "indexer STRING",
        "volume FLOAT",
        "fund STRING",
        "FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)"
    ],
    "cri_cra_dev.crm.operation_stages": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT NOT NULL",
        "name STRING NOT NULL",
        "order_index INT NOT NULL",
        "is_completed BOOLEAN"
    ],
    "cri_cra_dev.crm.projects": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "name STRING NOT NULL",
        "status STRING",
        "state STRING",
        "city STRING"
    ],
    "cri_cra_dev.crm.guarantees": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "name STRING NOT NULL",
        "type STRING",
        "value FLOAT",
        "description STRING"
    ],
    "cri_cra_dev.crm.operation_projects": [
        "operation_id BIGINT NOT NULL",
        "project_id BIGINT NOT NULL",
        "PRIMARY KEY (operation_id, project_id)"
    ],
    "cri_cra_dev.crm.operation_guarantees": [
        "operation_id BIGINT NOT NULL",
        "guarantee_id BIGINT NOT NULL",
        "PRIMARY KEY (operation_id, guarantee_id)"
    ],
    "cri_cra_dev.crm.rating_history": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT",
        "master_group_id BIGINT",
        "date TIMESTAMP NOT NULL",
        "rating_operation STRING NOT NULL",
        "rating_group STRING NOT NULL",
        "watchlist STRING",
        "sentiment STRING",
        "event_id BIGINT"
    ],
    "cri_cra_dev.crm.events": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT",
        "master_group_id BIGINT",
        "date TIMESTAMP NOT NULL",
        "type STRING NOT NULL",
        "title STRING NOT NULL",
        "description STRING NOT NULL",
        "registered_by STRING NOT NULL",
        "next_steps STRING",
        "completed_task_id STRING",
        "attention_points STRING",
        "our_attendees STRING",
        "operation_attendees STRING",
        "is_origination BOOLEAN",
        "operation_stage_id BIGINT"
    ],
    "cri_cra_dev.crm.task_rules": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT",
        "name STRING NOT NULL",
        "frequency STRING NOT NULL",
        "start_date TIMESTAMP",
        "end_date TIMESTAMP",
        "description STRING",
        "priority STRING",
        "is_origination BOOLEAN",
        "operation_stage_id BIGINT"
    ],
    "cri_cra_dev.crm.operation_review_notes": [
        "operation_id BIGINT PRIMARY KEY",
        "notes STRING",
        "updated_at TIMESTAMP NOT NULL",
        "updated_by STRING NOT NULL"
    ],
    "cri_cra_dev.crm.task_exceptions": [
        "task_id STRING PRIMARY KEY",
        "operation_id BIGINT",
        "deleted_at TIMESTAMP",
        "deleted_by STRING"
    ],
    "cri_cra_dev.crm.audit_logs": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "timestamp TIMESTAMP NOT NULL",
        "user_name STRING NOT NULL",
        "action STRING NOT NULL",
        "entity_type STRING NOT NULL",
        "entity_id STRING NOT NULL",
        "details STRING"
    ],
    "cri_cra_dev.crm.change_requests": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "title STRING NOT NULL",
        "description STRING NOT NULL",
        "requester STRING NOT NULL",
        "status STRING NOT NULL",
        "created_at TIMESTAMP NOT NULL",
        "updated_at TIMESTAMP NOT NULL"
    ],
    "cri_cra_dev.crm.patch_notes": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "version STRING NOT NULL",
        "date TIMESTAMP NOT NULL",
        "title STRING NOT NULL",
        "description STRING NOT NULL",
        "changes STRING NOT NULL"
    ],
    "cri_cra_dev.crm.sync_queue": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT NOT NULL",
        "data STRING NOT NULL",
        "created_at TIMESTAMP",
        "processed BOOLEAN"
    ],
    "cri_cra_dev.crm.analyst_notes": [
        "analyst_name STRING PRIMARY KEY",
        "notes STRING",
        "updated_at TIMESTAMP NOT NULL"
    ],
    "cri_cra_dev.crm.operation_risks": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT",
        "master_group_id BIGINT",
        "title STRING NOT NULL",
        "description STRING",
        "severity STRING",
        "created_at TIMESTAMP",
        "updated_at TIMESTAMP"
    ],
    "cri_cra_dev.crm.fund_allocation_inputs": [
        "fund_name STRING PRIMARY KEY",
        "emission FLOAT",
        "prepayment FLOAT",
        "repurchases FLOAT",
        "new_repo FLOAT",
        "updated_at TIMESTAMP"
    ]
}

def update_schema():
    conn = get_db_connection()
    try:
        with conn.cursor() as cursor:
            # 1. Process legacy renamed/deleted objects
            migrations = [
                ("ALTER TABLE cri_cra_dev.crm.structuring_operation_series RENAME TO cri_cra_dev.crm.operation_series", "Rename series table"),
                ("ALTER TABLE cri_cra_dev.crm.operation_series RENAME COLUMN structuring_operation_id TO operation_id", "Rename series col"),
                ("ALTER TABLE cri_cra_dev.crm.structuring_operation_stages RENAME TO cri_cra_dev.crm.operation_stages", "Rename stages table"),
                ("ALTER TABLE cri_cra_dev.crm.operation_stages RENAME COLUMN structuring_operation_id TO operation_id", "Rename stages col"),
                ("ALTER TABLE cri_cra_dev.crm.events RENAME COLUMN structuring_operation_stage_id TO operation_stage_id", "Rename events col"),
                ("ALTER TABLE cri_cra_dev.crm.task_rules RENAME COLUMN structuring_operation_stage_id TO operation_stage_id", "Rename tasks col"),
                ("DROP TABLE IF EXISTS cri_cra_dev.crm.structuring_operations", "Drop struct_operations"),
            ]
            for sql, desc in migrations:
                try:
                    cursor.execute(sql)
                    print(f"Migration applied: {desc}")
                except Exception:
                    # Ignore if the rename was already done or table missing
                    pass

            # 2. Re-create and Sync Columns for each Table
            for table_name, columns in SCHEMA.items():
                print(f"Ensuring schema logic for {table_name}...")
                
                # Build CREATE TABLE
                cols_sql = ",\n                    ".join(columns)
                create_sql = f"CREATE TABLE IF NOT EXISTS {table_name} (\n                    {cols_sql}\n                )"
                cursor.execute(create_sql)

                # Describe table to find missing columns
                try:
                    cursor.execute(f"DESCRIBE {table_name}")
                    existing_cols = {row.col_name.lower() for row in cursor.fetchall()}
                    
                    for col_def in columns:
                        if col_def.upper().startswith(("PRIMARY KEY", "FOREIGN KEY")):
                            continue
                        
                        parts = col_def.split(maxsplit=1)
                        col_name = parts[0]
                        
                        # Check if this column needs adding
                        if col_name.lower() not in existing_cols:
                            clean_type = parts[1]
                            # Remove IDENTITY and constraints syntax for the ADD COLUMN command
                            clean_type = re.sub(r'(?i)GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY', '', clean_type)
                            clean_type = re.sub(r'(?i)PRIMARY\s+KEY', '', clean_type)
                            # Removing NOT NULL so add column doesn't break due to existing data
                            clean_type = re.sub(r'(?i)NOT\s+NULL', '', clean_type)
                            clean_type = clean_type.strip()
                            
                            try:
                                alter_sql = f"ALTER TABLE {table_name} ADD COLUMN {col_name} {clean_type}"
                                cursor.execute(alter_sql)
                                print(f"  Added column {col_name} to {table_name}")
                            except Exception as e:
                                print(f"  Failed to add column {col_name} to {table_name}: {e}")
                except Exception as e:
                    print(f"Could not describe and sync columns for {table_name}: {e}")

            # 3. Post-sync adjustments (dropping NOT NULL constraints from old mandatory fields)
            nullable_cols = ['operation_type', 'maturity_date', 'responsible_analyst', 'review_frequency', 
                             'call_frequency', 'df_frequency', 'rating_operation', 'rating_group', 'watchlist']
            for col in nullable_cols:
                try:
                    cursor.execute(f"ALTER TABLE cri_cra_dev.crm.operations ALTER COLUMN {col} DROP NOT NULL")
                except Exception:
                    pass

            # Seed Patch notes
            cursor.execute("SELECT COUNT(*) as count FROM cri_cra_dev.crm.patch_notes")
            if cursor.fetchone().count == 0:
                print("Adding initial patch notes...")
                initial_changes = json.dumps(["Implementação inicial", "Gestão de operações unificada"])
                cursor.execute("""
                    INSERT INTO cri_cra_dev.crm.patch_notes (version, date, title, description, changes)
                    VALUES (?, ?, ?, ?, ?)
                """, ("1.0.0", datetime.now(), "Lançamento Inicial", "Primeira versão estável do sistema CRM.", initial_changes))

            conn.commit()
            print("Database schema updated successfully.")
    except Exception as e:
        print(f"Error updating schema: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    update_schema()
